// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  goombaId: __t.string().primaryKey(),
  spawnX: __t.f64(),
  spawnY: __t.f64(),
  spawnZ: __t.f64(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f64(),
  state: __t.string(),
  targetIdentity: __t.option(__t.string()),
  stateEndsAtMs: __t.f64(),
  nextChargeAllowedAtMs: __t.f64(),
  respawnAtMs: __t.option(__t.f64()),
  updatedAtMs: __t.f64(),
});
