// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkKey: __t.string().primaryKey(),
  chunkX: __t.f64(),
  chunkZ: __t.f64(),
  nextSpawnAtMs: __t.f64(),
  spawnSequence: __t.f64(),
  activeMysteryBoxId: __t.option(__t.string()),
  updatedAtMs: __t.f64(),
});
