// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerState", {
  identity: __t.string(),
  displayName: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f64(),
  pitch: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  planarSpeed: __t.f64(),
  motionState: __t.string(),
  lastInputSeq: __t.f64(),
  updatedAtMs: __t.f64(),
  lastCastAtMs: __t.f64(),
});


