// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("RingDropState", {
  ringId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  source: __t.string(),
  collected: __t.bool(),
  collectedBy: __t.option(__t.string()),
  collectedAtMs: __t.option(__t.f64()),
  spawnedAtMs: __t.f64(),
});


