import { GROUND_HALF_EXTENT } from "../../utils/constants";
import type { TreeSystemConfig } from "./types";

export const TREE_SYSTEM_CONFIG: TreeSystemConfig = {
  seed: 19437,
  variantsPerSpecies: 4,
  placement: {
    treeCount: 82,
    fieldRadius: GROUND_HALF_EXTENT - 3,
    clearingRadius: 11,
    minSpacing: 2.2,
    maxSlope: 0.95,
    rockClearance: 1.2,
    poissonAttempts: 30,
    maxPlacementAttempts: 12000,
    densityNoiseScale: 0.06,
    densityThreshold: 0.42,
    densityJitter: 0.22,
  },
  growth: {
    stepSize: 0.34,
    killDistance: 0.36,
    influenceRadius: 1.6,
    maxIterations: 92,
    trunkLiftBias: 0.55,
    lateralBias: 0.26,
    apicalDominance: 0.35,
  },
  radius: {
    gamma: 2,
    twigRadius: 0.04,
    minKeptRadius: 0.028,
  },
  meshing: {
    lodBranchRadialSegments: [6, 4, 3],
    lodCanopyDetail: [0, 0, 0],
    lodCanopySampleStride: [1, 2, 4],
    trunkDepthForLod2: 4,
  },
  lod: {
    updateHz: 8,
    lod0Distance: 16,
    lod1Distance: 30,
    lod2Distance: 52,
    hiddenDistance: 70,
    hysteresis: 2.5,
  },
  species: [
    {
      id: "round_oak",
      shape: "round",
      placementWeight: 0.42,
      trunkColor: "#5E4432",
      canopyColor: "#4E9A4B",
      trunkHeight: [2.3, 3.3],
      canopyHeight: [2.0, 3.4],
      canopyRadius: [1.35, 2.2],
      canopyPuffRadius: [0.36, 0.68],
      attractorCount: [110, 175],
      branchSpread: 0.8,
      lean: 0.08,
      windSkew: 0.18,
    },
    {
      id: "conical_pine",
      shape: "conical",
      placementWeight: 0.33,
      trunkColor: "#594533",
      canopyColor: "#3E7E43",
      trunkHeight: [2.9, 4.2],
      canopyHeight: [2.3, 3.8],
      canopyRadius: [1.1, 1.85],
      canopyPuffRadius: [0.28, 0.54],
      attractorCount: [95, 145],
      branchSpread: 0.56,
      lean: 0.06,
      windSkew: 0.12,
    },
    {
      id: "windswept_maple",
      shape: "windswept",
      placementWeight: 0.25,
      trunkColor: "#644A35",
      canopyColor: "#5AA851",
      trunkHeight: [2.2, 3.1],
      canopyHeight: [2.0, 3.0],
      canopyRadius: [1.45, 2.35],
      canopyPuffRadius: [0.34, 0.64],
      attractorCount: [105, 160],
      branchSpread: 0.9,
      lean: 0.12,
      windSkew: 0.42,
    },
  ],
};
