import { GROUND_HALF_EXTENT } from "../../utils/constants";
import type { TreeSystemConfig } from "./types";

export const TREE_SYSTEM_CONFIG: TreeSystemConfig = {
  seed: 19437,
  variantsPerSpecies: 4,
  placement: {
    treeCount: 176,
    fieldRadius: GROUND_HALF_EXTENT - 2.2,
    clearingRadius: 4.25,
    minSpacing: 1.9,
    maxSlope: 0.9,
    rockClearance: 1.2,
    poissonAttempts: 30,
    maxPlacementAttempts: 26000,
    densityNoiseScale: 0.05,
    densityThreshold: 0.32,
    densityJitter: 0.24,
  },
  growth: {
    stepSize: 0.44,
    killDistance: 0.42,
    influenceRadius: 2.1,
    maxIterations: 110,
    trunkLiftBias: 0.82,
    lateralBias: 0.34,
    apicalDominance: 0.58,
  },
  radius: {
    gamma: 2,
    twigRadius: 0.038,
    minKeptRadius: 0.03,
  },
  meshing: {
    lodBranchRadialSegments: [6, 4, 3],
    lodCanopyDetail: [2, 1, 0],
    lodCanopySampleStride: [1, 2, 5],
    trunkDepthForLod2: 4,
  },
  lod: {
    updateHz: 7,
    lod0Distance: 14,
    lod1Distance: 24,
    lod2Distance: 38,
    hiddenDistance: 58,
    hysteresis: 2.2,
  },
  species: [
    {
      id: "forest_pine",
      shape: "conical",
      placementWeight: 0.56,
      trunkColor: "#5F4732",
      canopyColor: "#3E7839",
      trunkHeight: [7.2, 12.6],
      canopyHeight: [5.8, 9.8],
      canopyRadius: [1.8, 3.2],
      canopyPuffRadius: [0.24, 0.46],
      attractorCount: [72, 116],
      branchSpread: 0.58,
      lean: 0.03,
      windSkew: 0.05,
    },
    {
      id: "coast_redwood",
      shape: "columnar",
      placementWeight: 0.3,
      trunkColor: "#6B4D35",
      canopyColor: "#437A3D",
      trunkHeight: [12, 19],
      canopyHeight: [5, 8.5],
      canopyRadius: [1.3, 2.2],
      canopyPuffRadius: [0.2, 0.4],
      attractorCount: [56, 88],
      branchSpread: 0.34,
      lean: 0.015,
      windSkew: 0.02,
    },
    {
      id: "slender_fir",
      shape: "conical",
      placementWeight: 0.14,
      trunkColor: "#5C4631",
      canopyColor: "#396E37",
      trunkHeight: [6, 10.2],
      canopyHeight: [5.4, 9.1],
      canopyRadius: [1.5, 2.7],
      canopyPuffRadius: [0.22, 0.42],
      attractorCount: [65, 102],
      branchSpread: 0.48,
      lean: 0.025,
      windSkew: 0.04,
    },
  ],
};
